name: Automated tests

on:
  push

jobs:
  test:
    runs-on: windows-latest  # указываем Windows
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # укажи нужную версию
      - name: Install Chrome
        run: |
          choco install googlechrome --ignore-checksums -y
        shell: powershell

      - name: Install dependencies
        run: pip install -r requirements

      - name: Run tests
        run: pytest
